services:
  web:
    build:
      context: '.'
    env_file: '.env'
    command: 'node -r dotenv/config build'
    restart: 'unless-stopped'
    ports:
      - 127.0.0.1:3000:3000
  database:
    image: surrealdb/surrealdb:latest
    ports:
      - 127.0.0.1:8000:8000
    command: 'start --log trace --user ${SURREAL_USER} --pass ${SURREAL_PASS}'
